report = new com.openbravo.pos.reports.PanelReportBean();

report.setTitleKey("Menu.StockByModel");
report.setReport("/com/openbravo/reports/stockbymodel");
report.setResourceBundle("com/openbravo/reports/modelreports_messages");

report.setSentence(
        "SELECT STOCKCURRENT.LOCATION AS LOCATIONID, LOCATIONS.NAME AS LOCATIONNAME, " +
        "PRODUCTS.REFERENCE, PRODUCTS.NAME, SUM(STOCKCURRENT.UNITS) AS UNITS " +
        "FROM STOCKCURRENT " +
        "JOIN LOCATIONS ON STOCKCURRENT.LOCATION = LOCATIONS.ID " +
        "JOIN PRODUCTS ON STOCKCURRENT.PRODUCT = PRODUCTS.ID " +
        "WHERE ?(QBF_FILTER) " +
        "GROUP BY STOCKCURRENT.LOCATION, LOCATIONS.NAME, PRODUCTS.REFERENCE, PRODUCTS.NAME " +
        "ORDER BY LOCATIONS.NAME, PRODUCTS.REFERENCE, PRODUCTS.NAME");
report.addParameter("PRODUCTS.NAME");
report.addParameter("PRODUCTS.PRICEBUY");
report.addParameter("PRODUCTS.PRICESELL");
report.addParameter("PRODUCTS.CATEGORY");
report.addParameter("PRODUCTS.CODE");
report.addParameter("PRODUCTS.BRAND");
report.addQBFFilter(new com.openbravo.pos.ticket.ProductFilter());
report.addParameter("STOCKCURRENT.LOCATION");
report.addQBFFilter(new com.openbravo.pos.reports.JParamsLocationWithFirst());

report.addField("LOCATIONID", com.openbravo.data.loader.Datas.STRING);
report.addField("LOCATIONNAME", com.openbravo.data.loader.Datas.STRING);
report.addField("REFERENCE", com.openbravo.data.loader.Datas.STRING);
report.addField("NAME", com.openbravo.data.loader.Datas.STRING);
report.addField("UNITS", com.openbravo.data.loader.Datas.DOUBLE);

report;
