//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.ticket;

import java.awt.event.ActionListener;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ListQBFModelNumber;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.user.EditorCreator;
import com.openbravo.pos.forms.AppLocal;

public class ProductFilterSales extends javax.swing.JPanel implements EditorCreator {

	/** Creates new form ProductFilterSales */
	public ProductFilterSales() {
		initComponents();

		m_jCboName.setModel(ListQBFModelNumber.getMandatoryString());
		m_jCboCategory.setModel(ListQBFModelNumber.getMandatoryString());
		m_jCboBrand.setModel(ListQBFModelNumber.getMandatoryString());
		m_jCboFamily.setModel(ListQBFModelNumber.getMandatoryString());
	}

	public void activate() {

		m_jtxtName.setText(null);
		m_jtxtCategory.setText(null);
		m_jtxtBrand.setText(null);
		m_jtxtFamily.setText(null);

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				m_jtxtName.requestFocus();
			}
		});
	}

	/** Search after the user pauses typing, so each keystroke does not hit the database. */
	public void addActionListener(ActionListener listener) {
		final javax.swing.Timer timer = new javax.swing.Timer(300, listener);
		timer.setRepeats(false);
		addDebouncedSearchListener(m_jtxtName, timer);
		addDebouncedSearchListener(m_jtxtCategory, timer);
		addDebouncedSearchListener(m_jtxtBrand, timer);
		addDebouncedSearchListener(m_jtxtFamily, timer);
		m_jCboName.addActionListener(e -> timer.restart());
		m_jCboCategory.addActionListener(e -> timer.restart());
		m_jCboBrand.addActionListener(e -> timer.restart());
		m_jCboFamily.addActionListener(e -> timer.restart());
	}

	private void addDebouncedSearchListener(javax.swing.JTextField field, javax.swing.Timer timer) {
		field.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
			@Override
			public void insertUpdate(javax.swing.event.DocumentEvent event) {
				timer.restart();
			}

			@Override
			public void removeUpdate(javax.swing.event.DocumentEvent event) {
				timer.restart();
			}

			@Override
			public void changedUpdate(javax.swing.event.DocumentEvent event) {
				timer.restart();
			}
		});
	}

	public Object createValue() throws BasicException {

		Object[] afilter = new Object[8];
		putStringFilter(afilter, 0, m_jCboName, m_jtxtName);
		putStringFilter(afilter, 2, m_jCboCategory, m_jtxtCategory);
		putStringFilter(afilter, 4, m_jCboBrand, m_jtxtBrand);
		putStringFilter(afilter, 6, m_jCboFamily, m_jtxtFamily);

		return afilter;
	}

	private void putStringFilter(Object[] afilter, int index, javax.swing.JComboBox compare,
			javax.swing.JTextField value) {
		String text = value.getText();
		if (text == null || text.equals("")) {
			afilter[index] = QBFCompareEnum.COMP_NONE;
			afilter[index + 1] = null;
		} else {
			afilter[index] = compare.getSelectedItem();
			afilter[index + 1] = text;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel5 = new javax.swing.JLabel();
		m_jCboName = new javax.swing.JComboBox();
		m_jtxtName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		m_jCboCategory = new javax.swing.JComboBox();
		m_jtxtCategory = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		m_jCboBrand = new javax.swing.JComboBox();
		m_jtxtBrand = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		m_jCboFamily = new javax.swing.JComboBox();
		m_jtxtFamily = new javax.swing.JTextField();

		setLayout(new java.awt.GridBagLayout());

		jLabel5.setText(AppLocal.getIntString("label.prodname")); // NOI18N
		jLabel2.setText(AppLocal.getIntString("label.prodcategory")); // NOI18N
		jLabel6.setText(AppLocal.getIntString("label.prodbrand")); // NOI18N
		jLabel7.setText(AppLocal.getIntString("label.prodfamily")); // NOI18N

		java.awt.GridBagConstraints labelConstraints = new java.awt.GridBagConstraints();
		labelConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		labelConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		labelConstraints.weightx = 1.0;
		labelConstraints.insets = new java.awt.Insets(5, 20, 5, 12);

		java.awt.GridBagConstraints comboConstraints = new java.awt.GridBagConstraints();
		comboConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		comboConstraints.weightx = 1.0;
		comboConstraints.insets = new java.awt.Insets(5, 0, 5, 12);

		java.awt.GridBagConstraints fieldConstraints = new java.awt.GridBagConstraints();
		fieldConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		fieldConstraints.weightx = 1.0;
		fieldConstraints.insets = new java.awt.Insets(5, 0, 5, 20);

		addFilterRow(jLabel5, m_jCboName, m_jtxtName, 0, labelConstraints, comboConstraints, fieldConstraints);
		addFilterRow(jLabel2, m_jCboCategory, m_jtxtCategory, 1, labelConstraints, comboConstraints,
				fieldConstraints);
		addFilterRow(jLabel6, m_jCboBrand, m_jtxtBrand, 2, labelConstraints, comboConstraints, fieldConstraints);
		addFilterRow(jLabel7, m_jCboFamily, m_jtxtFamily, 3, labelConstraints, comboConstraints, fieldConstraints);
	}// </editor-fold>//GEN-END:initComponents

	private void addFilterRow(javax.swing.JLabel label, javax.swing.JComboBox combo, javax.swing.JTextField field,
			int row, java.awt.GridBagConstraints labelConstraints, java.awt.GridBagConstraints comboConstraints,
			java.awt.GridBagConstraints fieldConstraints) {
		java.awt.GridBagConstraints labelRow = (java.awt.GridBagConstraints) labelConstraints.clone();
		labelRow.gridx = 0;
		labelRow.gridy = row;
		add(label, labelRow);

		java.awt.GridBagConstraints comboRow = (java.awt.GridBagConstraints) comboConstraints.clone();
		comboRow.gridx = 1;
		comboRow.gridy = row;
		add(combo, comboRow);

		java.awt.GridBagConstraints fieldRow = (java.awt.GridBagConstraints) fieldConstraints.clone();
		fieldRow.gridx = 2;
		fieldRow.gridy = row;
		add(field, fieldRow);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JComboBox m_jCboBrand;
	private javax.swing.JComboBox m_jCboCategory;
	private javax.swing.JComboBox m_jCboFamily;
	private javax.swing.JComboBox m_jCboName;
	private javax.swing.JTextField m_jtxtBrand;
	private javax.swing.JTextField m_jtxtCategory;
	private javax.swing.JTextField m_jtxtFamily;
	private javax.swing.JTextField m_jtxtName;
	// End of variables declaration//GEN-END:variables

}
