//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.ticket;

import java.awt.event.ActionListener;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ListQBFModelNumber;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.user.EditorCreator;
import com.openbravo.pos.forms.AppLocal;

public class ProductFilterSales extends javax.swing.JPanel implements EditorCreator {

	/** Creates new form ProductFilterSales */
	public ProductFilterSales() {
		initComponents();

		m_jCboName.setModel(ListQBFModelNumber.getMandatoryString());
		m_jCboCategory.setModel(ListQBFModelNumber.getMandatoryString());
		m_jCboBrand.setModel(ListQBFModelNumber.getMandatoryString());
	}

	public void activate() {

		m_jtxtBarCode.setText(null);
		m_jtxtName.setText(null);
		m_jtxtCategory.setText(null);
		m_jtxtBrand.setText(null);

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				m_jtxtName.requestFocus();
			}
		});
	}

	/** Pressing enter on any of the filter fields runs the search. */
	public void addActionListener(ActionListener listener) {
		m_jtxtBarCode.addActionListener(listener);
		m_jtxtName.addActionListener(listener);
		m_jtxtCategory.addActionListener(listener);
		m_jtxtBrand.addActionListener(listener);
	}

	public Object createValue() throws BasicException {

		Object[] afilter = new Object[8];
		putStringFilter(afilter, 0, m_jCboName, m_jtxtName);
		putStringFilter(afilter, 2, m_jCboCategory, m_jtxtCategory);
		putStringFilter(afilter, 4, m_jCboBrand, m_jtxtBrand);

		String sBarCode = m_jtxtBarCode.getText();
		if (sBarCode == null || sBarCode.equals("")) {
			afilter[6] = QBFCompareEnum.COMP_NONE;
			afilter[7] = null;
		} else {
			afilter[6] = QBFCompareEnum.COMP_CONTAINS;
			afilter[7] = sBarCode;
		}

		return afilter;
	}

	private void putStringFilter(Object[] afilter, int index, javax.swing.JComboBox compare,
			javax.swing.JTextField value) {
		String text = value.getText();
		if (text == null || text.equals("")) {
			afilter[index] = QBFCompareEnum.COMP_NONE;
			afilter[index + 1] = null;
		} else {
			afilter[index] = compare.getSelectedItem();
			afilter[index + 1] = text;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel5 = new javax.swing.JLabel();
		m_jCboName = new javax.swing.JComboBox();
		m_jtxtName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		m_jCboCategory = new javax.swing.JComboBox();
		m_jtxtCategory = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		m_jCboBrand = new javax.swing.JComboBox();
		m_jtxtBrand = new javax.swing.JTextField();
		m_jtxtBarCode = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();

		setPreferredSize(new java.awt.Dimension(570, 140));
		setLayout(null);

		jLabel5.setText(AppLocal.getIntString("label.prodname")); // NOI18N
		add(jLabel5);
		jLabel5.setBounds(20, 40, 110, 15);
		add(m_jCboName);
		m_jCboName.setBounds(130, 40, 130, 24);
		add(m_jtxtName);
		m_jtxtName.setBounds(270, 40, 290, 25);

		jLabel2.setText(AppLocal.getIntString("label.prodcategory")); // NOI18N
		add(jLabel2);
		jLabel2.setBounds(20, 70, 110, 15);
		add(m_jCboCategory);
		m_jCboCategory.setBounds(130, 70, 130, 24);
		add(m_jtxtCategory);
		m_jtxtCategory.setBounds(270, 70, 290, 25);

		jLabel6.setText(AppLocal.getIntString("label.prodbrand")); // NOI18N
		add(jLabel6);
		jLabel6.setBounds(20, 100, 110, 15);
		add(m_jCboBrand);
		m_jCboBrand.setBounds(130, 100, 130, 24);
		add(m_jtxtBrand);
		m_jtxtBrand.setBounds(270, 100, 290, 25);

		add(m_jtxtBarCode);
		m_jtxtBarCode.setBounds(270, 10, 290, 25);

		jLabel1.setText(AppLocal.getIntString("label.prodbarcode")); // NOI18N
		add(jLabel1);
		jLabel1.setBounds(20, 10, 110, 15);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JComboBox m_jCboBrand;
	private javax.swing.JComboBox m_jCboCategory;
	private javax.swing.JComboBox m_jCboName;
	private javax.swing.JTextField m_jtxtBarCode;
	private javax.swing.JTextField m_jtxtBrand;
	private javax.swing.JTextField m_jtxtCategory;
	private javax.swing.JTextField m_jtxtName;
	// End of variables declaration//GEN-END:variables

}
