-- Database upgrade script for DERBY
-- v2.30.3 - v2.30.4

CREATE TABLE GIFTVOUCHERS (
    ID VARCHAR(256) NOT NULL,
    CODE VARCHAR(64) NOT NULL,
    INITIALVALUE DOUBLE PRECISION NOT NULL,
    BALANCE DOUBLE PRECISION NOT NULL,
    ISSUEDRECEIPT VARCHAR(256) NOT NULL,
    ISSUEDLINE INTEGER NOT NULL,
    ISSUEDDATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT GIFTVOUCHERS_FK_RECEIPT FOREIGN KEY (ISSUEDRECEIPT) REFERENCES RECEIPTS(ID)
);
CREATE UNIQUE INDEX GIFTVOUCHERS_CODE_INX ON GIFTVOUCHERS(CODE);

INSERT INTO CATEGORIES(ID, NAME) VALUES ('gift-vouchers', 'Vals regal');
INSERT INTO PRODUCTS(ID, REFERENCE, CODE, NAME, PRICEBUY, PRICESELL, CATEGORY, TAXCAT, ISCOM, ISSCALE)
    VALUES ('gift-voucher-10', 'VAL10', 'VAL10', 'Val regal 10 EUR', 0, 10, 'gift-vouchers', '000', 0, 0);
INSERT INTO PRODUCTS(ID, REFERENCE, CODE, NAME, PRICEBUY, PRICESELL, CATEGORY, TAXCAT, ISCOM, ISSCALE)
    VALUES ('gift-voucher-20', 'VAL20', 'VAL20', 'Val regal 20 EUR', 0, 20, 'gift-vouchers', '000', 0, 0);
INSERT INTO PRODUCTS(ID, REFERENCE, CODE, NAME, PRICEBUY, PRICESELL, CATEGORY, TAXCAT, ISCOM, ISSCALE)
    VALUES ('gift-voucher-50', 'VAL50', 'VAL50', 'Val regal 50 EUR', 0, 50, 'gift-vouchers', '000', 0, 0);
INSERT INTO PRODUCTS(ID, REFERENCE, CODE, NAME, PRICEBUY, PRICESELL, CATEGORY, TAXCAT, ISCOM, ISSCALE)
    VALUES ('gift-voucher-100', 'VAL100', 'VAL100', 'Val regal 100 EUR', 0, 100, 'gift-vouchers', '000', 0, 0);
INSERT INTO PRODUCTS_CAT(PRODUCT, CATORDER) VALUES ('gift-voucher-10', 10);
INSERT INTO PRODUCTS_CAT(PRODUCT, CATORDER) VALUES ('gift-voucher-20', 20);
INSERT INTO PRODUCTS_CAT(PRODUCT, CATORDER) VALUES ('gift-voucher-50', 50);
INSERT INTO PRODUCTS_CAT(PRODUCT, CATORDER) VALUES ('gift-voucher-100', 100);

UPDATE RESOURCES SET CONTENT = $FILE{/com/openbravo/pos/templates/Printer.Ticket.xml} WHERE NAME = 'Printer.Ticket';
UPDATE RESOURCES SET CONTENT = $FILE{/com/openbravo/pos/templates/Printer.TicketPreview.xml} WHERE NAME = 'Printer.TicketPreview';
UPDATE RESOURCES SET CONTENT = $FILE{/com/openbravo/pos/templates/Printer.TicketGift.xml} WHERE NAME = 'Printer.TicketGift';
UPDATE RESOURCES SET CONTENT = $FILE{/com/openbravo/pos/templates/Printer.CustomerPaid.xml} WHERE NAME = 'Printer.CustomerPaid';

UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};
