-- Database upgrade script for DERBY
-- v2.30.2 - v2.30.3

ALTER TABLE PRODUCTS ADD COLUMN BRAND VARCHAR(256);
UPDATE PRODUCTS SET BRAND = 'Ysabel Mora' WHERE BRAND IS NULL;

UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{};
