CREATE TABLE STOCKSESSION (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    SUPPLIER VARCHAR(255),
    DELIVERYNOTE VARCHAR(255),
    LOCATION VARCHAR(255) NOT NULL,
    DATESTART TIMESTAMP NOT NULL,
    DATEEND TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    APPUSER VARCHAR(255) NOT NULL,
    CONSTRAINT STOCKSESSION_TYPE_CHECK CHECK (TYPE IN ('COUNT', 'RECEIPT')),
    CONSTRAINT STOCKSESSION_STATUS_CHECK CHECK (STATUS IN ('OPEN', 'POSTED')),
    CONSTRAINT STOCKSESSION_LOCATION_FK FOREIGN KEY (LOCATION) REFERENCES LOCATIONS(ID)
);
CREATE INDEX STOCKSESSION_OPEN_INX ON STOCKSESSION(STATUS, DATESTART);
CREATE TABLE STOCKSESSIONLINE (
    ID VARCHAR(255) NOT NULL PRIMARY KEY,
    STOCKSESSION VARCHAR(255) NOT NULL,
    PRODUCT VARCHAR(255),
    CODE VARCHAR(255) NOT NULL,
    ATTRIBUTESETINSTANCE_ID VARCHAR(255),
    UNITS DOUBLE PRECISION NOT NULL,
    SNAPSHOTUNITS DOUBLE PRECISION,
    TICKED SMALLINT NOT NULL DEFAULT 0,
    DATEFIRST TIMESTAMP NOT NULL,
    DATELAST TIMESTAMP NOT NULL,
    CONSTRAINT STOCKSESSIONLINE_SESSION_FK FOREIGN KEY (STOCKSESSION) REFERENCES STOCKSESSION(ID),
    CONSTRAINT STOCKSESSIONLINE_PRODUCT_FK FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID),
    CONSTRAINT STOCKSESSIONLINE_UNITS_CHECK CHECK (UNITS > 0),
    CONSTRAINT STOCKSESSIONLINE_TICK_CHECK CHECK (TICKED IN (0, 1))
);
CREATE UNIQUE INDEX STOCKSESSIONLINE_CODE_INX ON STOCKSESSIONLINE(STOCKSESSION, CODE);
ALTER TABLE STOCKDIARY ADD SUPPLIER VARCHAR(255);
ALTER TABLE STOCKDIARY ADD DELIVERYNOTE VARCHAR(255);
ALTER TABLE STOCKDIARY ADD STOCKSESSION VARCHAR(255);
